### ISSUE TITLE
Error when 2 alias have the same id

### ISSUE THREAD

**Issue by mflasquin** [PrestaShop/prestashop-shop-creator#17] opened 2022-10-18 15:43 UTC
**Describe the bug and add screenshots**

On generated datas if 2 alias are created with the same id, there is an error :
 
We have errors during the install ![image](https://user-images.githubusercontent.com/6594752/196466757-7392a7ac-6971-4158-9aba-6ab98f525d5e.png) 

**Steps to reproduce**

 1. Generate example datas with https://github.com/PrestaShop/prestashop-shop-creator.git
 2. make sure there is 2 alias with the same id in alias.xml
 3. Install Prestashop with demo data

**Comment by Progi1984** [comment] 2022-11-04 15:53
@mflasquin I didn't reproduce your bug.

In my `alias.xml`, I have with same id et no errors

```xml
    <alias id="quae" alias="quae" search="incidunt" active="1"/>
    <alias id="quae" alias="natus" search="ex" active="1"/>
```

**Comment by mflasquin** [comment] 2022-11-07 09:47
Hi @Progi1984,
I just reproduce this morning, the issue with the following alias.xml file :

`<?xml version="1.0" encoding="UTF-8"?>
<entity_alias>
  <fields id="alias" class="Alias">
    <field name="alias"/>
    <field name="search"/>
    <field name="active"/>
  </fields>
  <entities>
    <alias id="consequatur" alias="consequatur" search="facilis" active="1"/>
    <alias id="est" alias="consequatur" search="facilis" active="1"/>
  </entities>
</entity_alias>`

I've test on P8 develop branch.

**Comment by Progi1984** [comment] 2022-11-18 14:41
@mflasquin I didn't reproduce your bug. Sorry, but the install is ok with this file. :(

**Comment by Progi1984** [comment] 2022-11-25 14:06
@mflasquin Checked and the same problem with PHP 8.0.

**Comment by yanmakouf** [comment] 2022-11-29 22:48
Hello @Progi1984 , I am gonna pick up the subject following @mflasquin. I am a bit confused by the title of the issue. Just to be sure I understand the problem and its state of resolution : 1) We want to allow two aliases with the same id ? 🤔 and if so why ? To me id should be by default unique but maybe alias::id is something different...let me know.  2) So basically, you can reproduce the bug on this branch https://github.com/PrestaShop/prestashop-shop-creator/pull/18 only with PHP 8.0x ? Don't hesitate to ping me on slack if you wanna discuss more efficiently ;)

**Comment by mflasquin** [comment] 2022-11-30 07:59
> @mflasquin Checked and the same problem with PHP 8.0.

Can you try with another version of mariadb ? Or a fresh install of MySQL, maybe it's because of your db configuration ?

**Comment by FabienPapet** [comment] 2023-02-07 10:44
I just reproduced using 100 aliases

I had many times this line : 
`    <alias id="et" alias="et" search="accusamus" active="1"/>`

**Comment by matks** [comment] 2023-02-07 16:51
Hello guys, I think it is clear: since the data generated is random ; sometimes it will generate twice the same row 😄 

It's because random does not mean unique ! 😄 


I close this issue.
It does not mean there is no problem it just means this is not something we can work on right now. But I hope that thanks to @fabienpapet work it'll become a lot easier ;) because it might allow us to improve / isolate the random side

**Closed by matks** 2023-02-07 16:51 UTC
Labels: bug, Waiting for author
