### ISSUE TITLE
Error when 2 range weight for one carrier are generated

### ISSUE THREAD

**Issue by mflasquin** [PrestaShop/prestashop-shop-creator#19] opened 2022-10-24 14:12 UTC
**Describe the bug and add screenshots**

On generated datas if we are 2 line with same id_carrier and same delimiters in range_weight.xml, there is an error :

![image](https://user-images.githubusercontent.com/6594752/197546592-20d04066-e0a6-4b28-bbe4-2d3f16efce6f.png)

**Steps to reproduce**

 1. Generate example datas with https://github.com/PrestaShop/prestashop-shop-creator.git
 2. make sure there is 2 carrier with same delimiters in range_weight.xml
 3. Install Prestashop with demo data

**Comment by Progi1984** [comment] 2022-11-04 14:20
@mflasquin I didn't reproduce your bug.

In my `range_weight.xml`, I have with same `id_carrier` and same `delimiters`
```xml
    <range_weight id_carrier="iure" id="1" delimiter2="7997" delimiter1="0"/>
    <range_weight id_carrier="iure" id="2" delimiter2="7997" delimiter1="0"/>
```

**Comment by mflasquin** [comment] 2022-11-07 10:05
Hi @Progi1984,
I just reproduce this morning, the issue with the following range_weight.xml file :

`<?xml version="1.0" encoding="UTF-8"?>
<entity_range_weight>
  <fields class="RangeWeight">
    <field name="id_carrier" relation="carrier"/>
    <field name="delimiter1"/>
    <field name="delimiter2"/>
  </fields>
  <entities>
    <range_weight id_carrier="rerum" id="1" delimiter2="4180" delimiter1="0"/>
    <range_weight id_carrier="carrier_1" id="2" delimiter2="4180" delimiter1="0"/>
    <range_weight id_carrier="carrier_1" id="4" delimiter2="4180" delimiter1="0"/>
  </entities>
</entity_range_weight>`

I've test on P8 develop branch.

**Comment by matks** [comment] 2022-11-15 17:06
@Progi1984 Can you try reproducing the issue using the latest information provided by @mflasquin ?

**Comment by matks** [comment] 2023-02-07 16:48
Hello guys, since we could not reproduce this issue I think we should simply close this issue.

It does not mean there is no issue it just means this is not something we can work on right now. But I hope that thanks to @fabienpapet work it'll become a lot easier ;)

**Closed by matks** 2023-02-07 16:48 UTC
Labels: bug, Waiting for author
